### ISSUE TITLE
Problem in installation 

### ISSUE THREAD

**Issue by DsDastgheib** [kargaranamir/parstdex#12]
Hi, 
when I use `py -m pip install parstdex`  command I get the followings which states that there is something wrong with the package:

```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting parstdex
  Downloading parstdex-1.3.1-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.9/44.9 kB 170.8 kB/s eta 0:00:00
Collecting pytextspan~=0.5.0
  Downloading pytextspan-0.5.4.tar.gz (9.2 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

P. S. 1- I use python 3.10 version
2- Actually I wanted to use QuestionGenerator from [here](https://github.com/language-ml/parsi.io) but I got the error that states `ModuleNotFoundError: No module named 'parstdex'` and stopped with the above-mentioned problem. 

Any Idea how should I solve it? 
Thanks in advance

**Comment by kargaranamir** [comment]
Hi, Thanks for reaching out.
I was able to reproduce the error on python 3.10. This is because our package is dependent on the `pytextspan` package. I need to check which version of `pytextspan` is compatible with python3.10 and upgrade our `requirements.txt`. I will let you know. By the way, I also test our package on both python3.8 and 3.9, and the installation was successful.

**Comment by kargaranamir** [comment]
I opened an [issue](https://github.com/tamuhey/textspan/issues/7) in `pytextspan` regards of this issue, but if I don't get anything from them I will delete this dependency in the future and implement the features.  For now, I just can say if it's possible, continue your project on a lower version of pythons like 3.9, 3.8, or 3.7. Thanks.

**Comment by DsDastgheib** [comment]
Great! Thank you.
I used python 3.8 and as you said I did not get the above error. But I got a new error in generating questions. Do you mind checking [this issue](https://github.com/language-ml/parsi.io/issues/31) whenever you have time?

**Comment by kargaranamir** [comment]
Hi, 

Having [fixed](https://github.com/tamuhey/textspan/pull/8) the problem with `pytextspan` package, our package now works perfectly on Python3.10.
